trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nugetSource: 'https://api.nuget.org/v3/index.json'
  projectFile: './src/TheBlueSky.DotNet.Tools.SwiftHash.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: '$(projectFile)'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectFile)'
    includesymbols: true
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  displayName: 'Push to NuGet.og'
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/*.nupkg
      -s $(nugetSource)
      -k $(nuget.apikey)
      --skip-duplicate
